---
recipe_generation_attempts: 10000

minimum_recipe_score: 20

ingredient_max_grams: 500

number_of_ingredients:
  min: 5
  max: 10

include_ingredients:
  - Capsicum, red, fresh, raw
  - Carrot, mature, peeled, fresh
  - Chicken, breast, lean flesh
  - Egg, chicken, yolk, hard-boiled
  - fresh, boiled, drained
  - fresh, raw
  - Lime, native, fruit
  - Mussel, blue, steamed
  - Nut, almond, with skin, roasted, unsalted
  - Nut, brazil, raw or blanched, unsalted
  - Nut, cashew, roasted, unsalted
  - Nut, peanut, without skin, roasted
  - Oil, olive
  - Oyster, Pacific, aquacultured, raw
  - Paprika, dry powder
  - Pork, fillet
  - Salmon
  - Sardines
  - Seaweed, nori, dried
  - Seed, pumpkin, hulled & dried
  - Seed, sunflower
  - Spread, yeast, vegemite
  - Tahini, sesame seed pulp
  - Tomato, sundried
  - unpeeled, raw


exclude_ingredients:
  - liver
  - milk
  - taro
  - cassava

included_micronutrients:
  - Energy with dietary fibre, equated (kJ)
  - Protein (g)
  - Fat, total (g)
  - Biotin (B7) (ug)
  - Calcium (Ca) (mg)
  - Chloride (Cl) (mg)
  - Chromium (Cr) (ug)
  - Cobalamin (B12) (ug)
  - Cobalt (Co) (ug)
  - Copper (Cu) (mg)
  - Fluoride (F) (ug)
  - Folic acid (ug)
  - Iodine (I) (ug)
  - Iron (Fe) (mg)
  - Magnesium (Mg) (mg)
  - Manganese (Mn) (mg)
  - Niacin (B3) (mg)
  - Pantothenic acid (B5) (mg)
  - Phosphorus (P) (mg)
  - Potassium (K) (mg)
  - Pyridoxine (B6) (mg)
  - Riboflavin (B2) (mg)
  - Selenium (Se) (ug)
  - Thiamin (B1) (mg)
  - Total dietary fibre (g)
  - Vitamin A retinol equivalents (ug)
  - Vitamin C (mg)
  - Vitamin D3 equivalents (ug)
  - Vitamin E (mg)
  - Zinc (Zn) (mg)


nutrient_targets:
  - micronutrient: Energy with dietary fibre, equated (kJ)
    min: 8368
    max: 12552
  - micronutrient: Protein (g)
    min: 50
    max: 150
  - micronutrient: Fat, total (g)
    min: 50
    max: 150
  - micronutrient: Biotin (B7) (ug)
    min: 20
    max: 0
  - micronutrient: Calcium (Ca) (mg)
    min: 1
    max: 2.5
  - micronutrient: Chloride (Cl) (mg)
    min: 2.3
    max: 3.6
  - micronutrient: Chromium (Cr) (ug)
    min: 35
    max: 0
  - micronutrient: Cobalamin (B12) (ug)
    min: 2.4
    max: 0
  - micronutrient: Cobalt (Co) (ug)
    min: 5
    max: 0
  - micronutrient: Copper (Cu) (mg)
    min: 0.9
    max: 10
  - micronutrient: Fluoride (F) (ug)
    min: 3
    max: 0
  - micronutrient: Folic acid (ug)
    min: 400
    max: 1000
  - micronutrient: Iodine (I) (ug)
    min: 150
    max: 1100
  - micronutrient: Iron (Fe) (mg)
    min: 8
    max: 45
  - micronutrient: Magnesium (Mg) (mg)
    min: 420
    max: 0
  - micronutrient: Manganese (Mn) (mg)
    min: 2.3
    max: 11
  - micronutrient: Niacin (B3) (mg)
    min: 16
    max: 35
  - micronutrient: Pantothenic acid (B5) (mg)
    min: 5
    max: 0
  - micronutrient: Phosphorus (P) (mg)
    min: 0.7
    max: 4
  - micronutrient: Potassium (K) (mg)
    min: 3.5
    max: 0
  - micronutrient: Pyridoxine (B6) (mg)
    min: 1.3
    max: 100
  - micronutrient: Riboflavin (B2) (mg)
    min: 1.3
    max: 0
  - micronutrient: Selenium (Se) (ug)
    min: 55
    max: 200
  - micronutrient: Thiamin (B1) (mg)
    min: 1.2
    max: 0
  - micronutrient: Total dietary fibre (g)
    min: 28
    max: 0
  - micronutrient: Vitamin A retinol equivalents (ug)
    min: 3000
    max: 10000
  - micronutrient: Vitamin C (mg)
    min: 90
    max: 2000
  - micronutrient: Vitamin D3 equivalents (ug)
    min: 600
    max: 4000
  - micronutrient: Vitamin E (mg)
    min: 20
    max: 1000
  - micronutrient: Zinc (Zn) (mg)
    min: 11
    max: 40
